//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagerClient.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRManagerClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 学历 的本地化字符串。
        /// </summary>
        public static string ArguType_EduBack {
            get {
                return ResourceManager.GetString("ArguType_EduBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 休假类型 的本地化字符串。
        /// </summary>
        public static string ArguType_LeaveType {
            get {
                return ResourceManager.GetString("ArguType_LeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 民族 的本地化字符串。
        /// </summary>
        public static string ArguType_Nation {
            get {
                return ResourceManager.GetString("ArguType_Nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加班类型 的本地化字符串。
        /// </summary>
        public static string ArguType_OverWorkType {
            get {
                return ResourceManager.GetString("ArguType_OverWorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补签原因 的本地化字符串。
        /// </summary>
        public static string ArguType_ReSignInReasonType {
            get {
                return ResourceManager.GetString("ArguType_ReSignInReasonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补签类型 的本地化字符串。
        /// </summary>
        public static string ArguType_ReSignInType {
            get {
                return ResourceManager.GetString("ArguType_ReSignInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司 的本地化字符串。
        /// </summary>
        public static string CardFillRecordType_Company {
            get {
                return ResourceManager.GetString("CardFillRecordType_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人 的本地化字符串。
        /// </summary>
        public static string CardFillRecordType_Personal {
            get {
                return ResourceManager.GetString("CardFillRecordType_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周五 的本地化字符串。
        /// </summary>
        public static string DayOfWeek_Friday {
            get {
                return ResourceManager.GetString("DayOfWeek_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周一 的本地化字符串。
        /// </summary>
        public static string DayOfWeek_Monday {
            get {
                return ResourceManager.GetString("DayOfWeek_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周六 的本地化字符串。
        /// </summary>
        public static string DayOfWeek_Saturday {
            get {
                return ResourceManager.GetString("DayOfWeek_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周日 的本地化字符串。
        /// </summary>
        public static string DayOfWeek_Sunday {
            get {
                return ResourceManager.GetString("DayOfWeek_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周四 的本地化字符串。
        /// </summary>
        public static string DayOfWeek_Thursday {
            get {
                return ResourceManager.GetString("DayOfWeek_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周二 的本地化字符串。
        /// </summary>
        public static string DayOfWeek_Tuesday {
            get {
                return ResourceManager.GetString("DayOfWeek_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周三 的本地化字符串。
        /// </summary>
        public static string DayOfWeek_Wednesday {
            get {
                return ResourceManager.GetString("DayOfWeek_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降职 的本地化字符串。
        /// </summary>
        public static string RankStatusEnum_Down {
            get {
                return ResourceManager.GetString("RankStatusEnum_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平职 的本地化字符串。
        /// </summary>
        public static string RankStatusEnum_Even {
            get {
                return ResourceManager.GetString("RankStatusEnum_Even", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转正 的本地化字符串。
        /// </summary>
        public static string RankStatusEnum_ToFull {
            get {
                return ResourceManager.GetString("RankStatusEnum_ToFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升职 的本地化字符串。
        /// </summary>
        public static string RankStatusEnum_Up {
            get {
                return ResourceManager.GetString("RankStatusEnum_Up", resourceCulture);
            }
        }
    }
}
